export default [
  {
    q: "Waste no more time arguing about what a good man should be. Be one.",
    a: "Marcus Aurelius",
    c: "67",
    h: "<blockquote>&ldquo;Waste no more time arguing about what a good man should be. Be one.&rdquo; &mdash; <footer>Marcus Aurelius</footer></blockquote>",
  },
  {
    q: "In three words I can sum up everything I've learned about life: it goes on.",
    a: "Robert Frost",
    c: "75",
    h: "<blockquote>&ldquo;In three words I can sum up everything I've learned about life: it goes on.&rdquo; &mdash; <footer>Robert Frost</footer></blockquote>",
  },
  {
    q: "A man is great not because he hasn't failed; a man is great because failure hasn't stopped him.",
    a: "Confucius",
    c: "95",
    h: "<blockquote>&ldquo;A man is great not because he hasn't failed; a man is great because failure hasn't stopped him.&rdquo; &mdash; <footer>Confucius</footer></blockquote>",
  },
  {
    q: "Some people feel the rain. Others just get wet. ",
    a: "Bob Dylan",
    c: "48",
    h: "<blockquote>&ldquo;Some people feel the rain. Others just get wet. &rdquo; &mdash; <footer>Bob Dylan</footer></blockquote>",
  },
  {
    q: "Insanity: doing the same thing over and over again and expecting different results.",
    a: "Albert Einstein",
    c: "83",
    h: "<blockquote>&ldquo;Insanity: doing the same thing over and over again and expecting different results.&rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
  },
  {
    q: "You need a plan to build a house. To build a life, it is even more important to have a plan or goal.",
    a: "Zig Ziglar",
    c: "100",
    h: "<blockquote>&ldquo;You need a plan to build a house. To build a life, it is even more important to have a plan or goal.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "Honesty is the first chapter in the book of wisdom.",
    a: "Thomas Jefferson",
    c: "51",
    h: "<blockquote>&ldquo;Honesty is the first chapter in the book of wisdom.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "Great things are not done by impulse, but by a series of small things brought together.",
    a: "Vincent van Gogh",
    c: "87",
    h: "<blockquote>&ldquo;Great things are not done by impulse, but by a series of small things brought together.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "Unexpressed emotions will never die. They are buried alive and will come forth later in uglier ways.",
    a: "Sigmund Freud",
    c: "100",
    h: "<blockquote>&ldquo;Unexpressed emotions will never die. They are buried alive and will come forth later in uglier ways.&rdquo; &mdash; <footer>Sigmund Freud</footer></blockquote>",
  },
  {
    q: "Trust is the foundation of great leadership.",
    a: "Lolly Daskal",
    c: "44",
    h: "<blockquote>&ldquo;Trust is the foundation of great leadership.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "I would rather die on my feet than live on my knees.",
    a: "Euripides",
    c: "52",
    h: "<blockquote>&ldquo;I would rather die on my feet than live on my knees.&rdquo; &mdash; <footer>Euripides</footer></blockquote>",
  },
  {
    q: "The danger of an adventure is worth a thousand days of ease and comfort.",
    a: "Paulo Coelho",
    c: "72",
    h: "<blockquote>&ldquo;The danger of an adventure is worth a thousand days of ease and comfort.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "Thoughts become things. If you see it in your mind, you will hold it in your hand.",
    a: "Bob Proctor",
    c: "82",
    h: "<blockquote>&ldquo;Thoughts become things. If you see it in your mind, you will hold it in your hand.&rdquo; &mdash; <footer>Bob Proctor</footer></blockquote>",
  },
  {
    q: "We cannot expect to be happy always... by experiencing evil as well as good we become wise.",
    a: "Hans Christian Andersen",
    c: "91",
    h: "<blockquote>&ldquo;We cannot expect to be happy always... by experiencing evil as well as good we become wise.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
  },
  {
    q: "I succeeded by saying what everyone else is thinking.",
    a: "Joan Rivers",
    c: "53",
    h: "<blockquote>&ldquo;I succeeded by saying what everyone else is thinking.&rdquo; &mdash; <footer>Joan Rivers</footer></blockquote>",
  },
  {
    q: "Don't give up on your dreams, or your dreams will give up on you.",
    a: "John Wooden",
    c: "65",
    h: "<blockquote>&ldquo;Don't give up on your dreams, or your dreams will give up on you.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
  },
  {
    q: "The important thing is not what one is born with but what use one makes of that equipment.",
    a: "Alfred Adler",
    c: "90",
    h: "<blockquote>&ldquo;The important thing is not what one is born with but what use one makes of that equipment.&rdquo; &mdash; <footer>Alfred Adler</footer></blockquote>",
  },
  {
    q: "Educating the mind without educating the heart is no education at all.",
    a: "Aristotle",
    c: "70",
    h: "<blockquote>&ldquo;Educating the mind without educating the heart is no education at all.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
  },
  {
    q: "Only to the extent that we expose ourselves over and over to annihilation can that which is indestructible in us be found.",
    a: "Pema Chodron",
    c: "122",
    h: "<blockquote>&ldquo;Only to the extent that we expose ourselves over and over to annihilation can that which is indestructible in us be found.&rdquo; &mdash; <footer>Pema Chodron</footer></blockquote>",
  },
  {
    q: "If we will be quiet and ready enough, we shall find compensation in every disappointment.",
    a: "Henry David Thoreau",
    c: "89",
    h: "<blockquote>&ldquo;If we will be quiet and ready enough, we shall find compensation in every disappointment.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
  },
  {
    q: "The chief cause of failure and unhappiness is trading what you want most for what you want right now.",
    a: "Zig Ziglar",
    c: "101",
    h: "<blockquote>&ldquo;The chief cause of failure and unhappiness is trading what you want most for what you want right now.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "Winners are not people who never fail, but people who never quit.",
    a: "Arnold Schwarzenegger",
    c: "65",
    h: "<blockquote>&ldquo;Winners are not people who never fail, but people who never quit.&rdquo; &mdash; <footer>Arnold Schwarzenegger</footer></blockquote>",
  },
  {
    q: "Do not look for approval except for the consciousness of doing your best.",
    a: "Andrew Carnegie",
    c: "73",
    h: "<blockquote>&ldquo;Do not look for approval except for the consciousness of doing your best.&rdquo; &mdash; <footer>Andrew Carnegie</footer></blockquote>",
  },
  {
    q: "You don't need to be better than anyone else, you just need to be better than you used to be.",
    a: "Wayne Dyer",
    c: "93",
    h: "<blockquote>&ldquo;You don't need to be better than anyone else, you just need to be better than you used to be.&rdquo; &mdash; <footer>Wayne Dyer</footer></blockquote>",
  },
  {
    q: "To escape from the world means that one's mind is not concerned with the opinions of the world.",
    a: "Dogen",
    c: "95",
    h: "<blockquote>&ldquo;To escape from the world means that one's mind is not concerned with the opinions of the world.&rdquo; &mdash; <footer>Dogen</footer></blockquote>",
  },
  {
    q: "For fast-acting relief try slowing down.",
    a: "Lily Tomlin",
    c: "40",
    h: "<blockquote>&ldquo;For fast-acting relief try slowing down.&rdquo; &mdash; <footer>Lily Tomlin</footer></blockquote>",
  },
  {
    q: "To find yourself, think for yourself.",
    a: "Socrates",
    c: "37",
    h: "<blockquote>&ldquo;To find yourself, think for yourself.&rdquo; &mdash; <footer>Socrates</footer></blockquote>",
  },
  {
    q: "The law of harvest is to reap more than you sow. Sow an act, and you reap a habit. Sow a habit and you reap a character. Sow a character and you reap a destiny.",
    a: "James Allen",
    c: "160",
    h: "<blockquote>&ldquo;The law of harvest is to reap more than you sow. Sow an act, and you reap a habit. Sow a habit and you reap a character. Sow a character and you reap a destiny.&rdquo; &mdash; <footer>James Allen</footer></blockquote>",
  },
  {
    q: "If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.",
    a: "Mark Twain",
    c: "131",
    h: "<blockquote>&ldquo;If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
  },
  {
    q: "The most important battle is one to conquer yourself.",
    a: "Yanni",
    c: "53",
    h: "<blockquote>&ldquo;The most important battle is one to conquer yourself.&rdquo; &mdash; <footer>Yanni</footer></blockquote>",
  },
  {
    q: "It's easy to wish for health when you're sick.  When you're doing well, you need just as much vigilance.",
    a: "Kamal Ravikant",
    c: "104",
    h: "<blockquote>&ldquo;It's easy to wish for health when you're sick.  When you're doing well, you need just as much vigilance.&rdquo; &mdash; <footer>Kamal Ravikant</footer></blockquote>",
  },
  {
    q: "Do it with passion, or not at all.",
    a: "Rosa Nouchette Carey",
    c: "34",
    h: "<blockquote>&ldquo;Do it with passion, or not at all.&rdquo; &mdash; <footer>Rosa Nouchette Carey</footer></blockquote>",
  },
  {
    q: "To himself everyone is immortal; he may know that he is going to die, but he can never know he is dead.",
    a: "Samuel Butler",
    c: "103",
    h: "<blockquote>&ldquo;To himself everyone is immortal; he may know that he is going to die, but he can never know he is dead.&rdquo; &mdash; <footer>Samuel Butler</footer></blockquote>",
  },
  {
    q: "When you love someone, you love the person as they are, and not as you'd like them to be.",
    a: "Leo Tolstoy",
    c: "89",
    h: "<blockquote>&ldquo;When you love someone, you love the person as they are, and not as you'd like them to be.&rdquo; &mdash; <footer>Leo Tolstoy</footer></blockquote>",
  },
  {
    q: "Curiosity is the most powerful thing you own.",
    a: "James Cameron",
    c: "45",
    h: "<blockquote>&ldquo;Curiosity is the most powerful thing you own.&rdquo; &mdash; <footer>James Cameron</footer></blockquote>",
  },
  {
    q: "Turn the pain into power.",
    a: "Unknown",
    c: "25",
    h: "<blockquote>&ldquo;Turn the pain into power.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Sometimes you have to shut your eyes, so you can see the real beauty.",
    a: "Kilian Jornet",
    c: "69",
    h: "<blockquote>&ldquo;Sometimes you have to shut your eyes, so you can see the real beauty.&rdquo; &mdash; <footer>Kilian Jornet</footer></blockquote>",
  },
  {
    q: "Every second you have on this planet is very precious and it's your responsibility that you're happy.",
    a: "Naval Ravikant",
    c: "101",
    h: "<blockquote>&ldquo;Every second you have on this planet is very precious and it's your responsibility that you're happy.&rdquo; &mdash; <footer>Naval Ravikant</footer></blockquote>",
  },
  {
    q: "Appear weak when you are strong, and strong when you are weak.",
    a: "Sun Tzu",
    c: "62",
    h: "<blockquote>&ldquo;Appear weak when you are strong, and strong when you are weak.&rdquo; &mdash; <footer>Sun Tzu</footer></blockquote>",
  },
  {
    q: "Decide upon your major definite purpose in life and then organize all your activities around it.",
    a: "Brian Tracy",
    c: "96",
    h: "<blockquote>&ldquo;Decide upon your major definite purpose in life and then organize all your activities around it.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "Realize deeply that the present moment is all you ever have. ",
    a: "Eckhart Tolle",
    c: "61",
    h: "<blockquote>&ldquo;Realize deeply that the present moment is all you ever have. &rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "Don't be afraid to see what you see.",
    a: "Ronald Reagan",
    c: "36",
    h: "<blockquote>&ldquo;Don't be afraid to see what you see.&rdquo; &mdash; <footer>Ronald Reagan</footer></blockquote>",
  },
  {
    q: "Happiness is a quality of the soul...not a function of one's material circumstances.",
    a: "Aristotle",
    c: "84",
    h: "<blockquote>&ldquo;Happiness is a quality of the soul...not a function of one's material circumstances.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
  },
  {
    q: "Wisdom is the oneness of mind that guides and permeates all things.",
    a: "Heraclitus",
    c: "67",
    h: "<blockquote>&ldquo;Wisdom is the oneness of mind that guides and permeates all things.&rdquo; &mdash; <footer>Heraclitus</footer></blockquote>",
  },
  {
    q: "When you change what you believe, you change what you do.",
    a: "Spencer Johnson",
    c: "57",
    h: "<blockquote>&ldquo;When you change what you believe, you change what you do.&rdquo; &mdash; <footer>Spencer Johnson</footer></blockquote>",
  },
  {
    q: "Believe and you're halfway there.",
    a: "Harry S. Truman",
    c: "33",
    h: "<blockquote>&ldquo;Believe and you're halfway there.&rdquo; &mdash; <footer>Harry S. Truman</footer></blockquote>",
  },
  {
    q: "Let us always meet each other with smile, for the smile is the beginning of love.",
    a: "Mother Teresa",
    c: "81",
    h: "<blockquote>&ldquo;Let us always meet each other with smile, for the smile is the beginning of love.&rdquo; &mdash; <footer>Mother Teresa</footer></blockquote>",
  },
  {
    q: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    a: "Mahatma Gandhi",
    c: "74",
    h: "<blockquote>&ldquo;Live as if you were to die tomorrow. Learn as if you were to live forever.&rdquo; &mdash; <footer>Mahatma Gandhi</footer></blockquote>",
  },
  {
    q: "You find peace not by rearranging the circumstances of your life, but by realizing who you are at the deepest level.",
    a: "Eckhart Tolle",
    c: "116",
    h: "<blockquote>&ldquo;You find peace not by rearranging the circumstances of your life, but by realizing who you are at the deepest level.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "The first rule of handling conflict is don't hang around people who are constantly engaging in conflict.",
    a: "Naval Ravikant",
    c: "104",
    h: "<blockquote>&ldquo;The first rule of handling conflict is don't hang around people who are constantly engaging in conflict.&rdquo; &mdash; <footer>Naval Ravikant</footer></blockquote>",
  },
];
